name: Test Lima
on: [push]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Install Lima
        run: |
          brew install lima docker
          lima start --name default
          docker info
